import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NavMenu, Footer, AppShell } from "@/components/layout";
import { DevicesProvider } from "@/contexts/DevicesContext";
import { EnvironmentsProvider } from "@/contexts/EnvironmentsContext";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <EnvironmentsProvider>
          <DevicesProvider>
            <AppShell>
              {children}
            </AppShell>
          </DevicesProvider>
        </EnvironmentsProvider>
      </body>
    </html>
  );
}
